"""
Personalized roadmap generation.

POST /roadmap/generate — takes a career_id, fetches the REAL gap
analysis (same backend logic from Sprint 4, never recalculated by
AI), sends that gap data to Groq to generate an ORDERED, EXPLAINED
roadmap, validates the AI's response before saving anything, then
persists the roadmap to Supabase.

IMPORTANT: Groq is used ONLY to explain and sequence steps in
natural language. It never invents skill levels, gaps, or scores —
those are always computed by our own backend logic (careers.py),
matching the BRD's core design principle.

PROMPT ENGINEERING NOTES:
- response_format={"type": "json_object"} forces valid JSON at the
  API level (Groq's structured output feature), not just via prompt
  instruction — this is strictly more reliable than asking nicely.
- Because JSON mode requires a top-level OBJECT (not a bare array),
  the model is asked to return {"steps": [...]} rather than a bare
  [...] array, and parsing below expects that shape.
- Defensive parsing/validation still happens on top of JSON mode,
  since JSON mode guarantees syntactically valid JSON, but not that
  the CONTENT is correct (e.g. it could still return an empty list,
  or reference a skill not in our real gap data) — never trust AI
  output blindly, even with structured output enabled.

EXISTING ROADMAP BEHAVIOR:
- If the user already has a roadmap for this career, we return the
  EXISTING one instead of generating a new one — avoids wasting a
  Groq API call and creating duplicate database rows every time the
  user simply revisits this page.
- The response includes `already_existed: true` in this case, so
  the frontend can show the user an honest message rather than
  silently returning old data with no indication.
- KNOWN LIMITATION: this does NOT check whether the user's skills
  have changed since the roadmap was generated (e.g. they retook an
  assessment and improved). Staleness detection + regeneration is
  planned for a future recalculation feature.

RESOURCE LINKS:
- Resource URLs are NEVER generated by AI — the prompt explicitly
  forbids Groq from inventing them, since a hallucinated link is
  worse than no link at all (broken or fake URLs actively mislead
  the user). Instead, each real skill in our system maps to one
  hand-picked, verified, real learning resource in SKILL_RESOURCES
  below. This is simple and safe precisely because we only have a
  small, fixed set of skills — if the skill catalog grows much
  larger, this could move into its own database table instead.

STEP_ID AND IS_COMPLETED (added for progress tracking):
- Each returned step now includes its real database `step_id` and
  current `is_completed` state — previously missing, which meant
  the frontend had no way to call POST /progress/update or
  POST /progress/activity for a specific step, since those
  endpoints require the real step_id. Freshly generated steps
  always start is_completed=False (nothing has been done yet);
  existing steps return their real, current completion state.
"""

import json
from fastapi import APIRouter, Depends, HTTPException
from groq import Groq
from app.core.auth import get_current_user_id
from app.core.config import settings
from app.db.database import get_supabase
from app.schemas.roadmap import RoadmapGenerateRequest, RoadmapResponse, RoadmapStepOut, RoadmapRecalculateRequest

router = APIRouter()


# Curated learning resources per skill — hand-picked, real URLs,
# never AI-generated. Keyed by the exact skill name as stored in
# the `skills` table. If a skill has no entry here, resource_url
# will simply be None for that step, which the frontend already
# handles gracefully (no broken link shown).
SKILL_RESOURCES = {
    "Python": "https://docs.python.org/3/tutorial/",
    "SQL": "https://www.w3schools.com/sql/",
    "JavaScript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    "Statistics": "https://www.khanacademy.org/math/statistics-probability",
    "Machine Learning": "https://www.coursera.org/learn/machine-learning",
    "Data Visualization": "https://www.tableau.com/learn/training",
}


def build_roadmap_prompt(career_title: str, skill_gaps: list[dict]) -> str:
    """
    Builds the prompt sent to Groq for roadmap generation.

    Prompt engineering principles applied:
    - Clear role assignment
    - Structured, explicit input data (not vague prose)
    - Strict, exemplified output schema (a JSON OBJECT, matching
      the response_format="json_object" requirement)
    - Explicit constraints preventing hallucinated skills/numbers
    - Instruction to ground every step in the provided gap data only
    - "Return ONLY this JSON object" stated at the end too —
      repetition of the key constraint improves compliance
    """
    gap_lines = "\n".join(
        f"- {g['skill_name']}: current level {g['current_level']}%, "
        f"required level {g['required_level']}%, gap {g['gap']} points, "
        f"importance {g['importance']}/3"
        for g in skill_gaps
    )

    prompt = f"""You are a career development assistant that creates personalized learning roadmaps.

TASK:
Create an ordered, personalized learning roadmap to help a user reach the career "{career_title}".

INPUT DATA (the user's ACTUAL skill gaps, calculated by the system — this is the ONLY data you may use):
{gap_lines}

RULES YOU MUST FOLLOW:
1. Only create roadmap steps for the skills listed above. Do not invent, add, or reference any skill not explicitly listed in the input data.
2. Order the steps by priority: skills with the largest gap and highest importance should come first.
3. Skills with a gap of 0 should NOT appear in the roadmap — they are already met and require no further steps.
4. For each step, write a short, encouraging, specific title and a 1-2 sentence description explaining what to focus on and why it matters for this career.
5. Do not invent specific external resource URLs.
6. Do not include any commentary, explanation, or text outside the JSON object.

OUTPUT FORMAT:
Return a JSON OBJECT with a single key "steps", containing an array of step objects, in this EXACT structure, with no additional keys and no surrounding text:

{{
  "steps": [
    {{
      "step_order": 1,
      "title": "Short, specific step title",
      "description": "1-2 sentence explanation of what to do and why.",
      "skill_name": "Exact skill name from the input data above"
    }}
  ]
}}

Return ONLY this JSON object."""

    return prompt


def parse_and_validate_ai_response(raw_text: str, valid_skill_names: set[str]) -> list[dict]:
    """
    Defensively parses Groq's response and validates it before we
    trust any of it. This is the critical safety step: we NEVER
    save malformed or hallucinated AI output directly to the
    database. If validation fails at any point, we raise an error
    instead of silently saving bad data.

    Note: even with response_format="json_object" guaranteeing
    SYNTACTICALLY valid JSON, we still validate the CONTENT here —
    JSON mode doesn't guarantee the model followed our business
    rules (e.g. only using real skill names).
    """
    cleaned = raw_text.strip()

    # Defensive fallback: some models still wrap JSON in markdown
    # code fences even in JSON mode. Strip this just in case.
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        if cleaned.startswith("json"):
            cleaned = cleaned[4:]
        cleaned = cleaned.strip()

    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        raise HTTPException(
            status_code=502,
            detail="AI returned an invalid response format. Please try again.",
        )

    if not isinstance(parsed, dict) or "steps" not in parsed:
        raise HTTPException(
            status_code=502,
            detail="AI response was not a valid roadmap object.",
        )

    steps_list = parsed["steps"]
    if not isinstance(steps_list, list):
        raise HTTPException(
            status_code=502,
            detail="AI response 'steps' was not a valid list.",
        )

    validated_steps = []
    for item in steps_list:
        # Reject any step referencing a skill that wasn't actually
        # in our real gap data — this is the hard guard against
        # hallucinated skills sneaking into the saved roadmap.
        if not isinstance(item, dict):
            continue
        skill_name = item.get("skill_name")
        if skill_name not in valid_skill_names:
            continue
        if not item.get("title") or not item.get("description"):
            continue

        validated_steps.append(item)

    if not validated_steps:
        raise HTTPException(
            status_code=502,
            detail="AI did not return any valid roadmap steps. Please try again.",
        )

    return validated_steps


@router.post("/roadmap/generate", response_model=RoadmapResponse)
async def generate_roadmap(
    request: RoadmapGenerateRequest,
    user_id: str = Depends(get_current_user_id),
):
    """
    Generates a personalized roadmap for the current user toward
    a specific career, using their REAL gap analysis as grounding
    data for Groq. Returns an existing roadmap instead of generating
    a new one if the user already has one for this career.
    """
    supabase = get_supabase()

    # ------------------------------------------------------------
    # STEP 1 — Fetch the career and REAL gap data, reusing the
    # exact same backend logic as Sprint 4's gap analysis endpoint.
    # This is never recalculated or guessed by AI.
    # ------------------------------------------------------------
    career_result = (
        supabase.table("careers")
        .select("id, title")
        .eq("id", request.career_id)
        .single()
        .execute()
    )

    if not career_result.data:
        raise HTTPException(status_code=404, detail="Career not found.")

    career_title = career_result.data["title"]

    requirements_result = (
        supabase.table("career_skills")
        .select("skill_id, required_level, importance, skills(name)")
        .eq("career_id", request.career_id)
        .execute()
    )
    requirements = requirements_result.data or []

    if not requirements:
        raise HTTPException(
            status_code=404, detail="No skill requirements defined for this career."
        )

    skill_ids = [req["skill_id"] for req in requirements]
    user_skills_result = (
        supabase.table("user_skills")
        .select("skill_id, assessed_level")
        .eq("profile_id", user_id)
        .in_("skill_id", skill_ids)
        .execute()
    )
    user_skill_levels = {
        row["skill_id"]: row["assessed_level"] or 0
        for row in (user_skills_result.data or [])
    }

    gap_data = []
    total_required = 0
    total_current = 0
    for req in requirements:
        skill_id = req["skill_id"]
        required_level = req["required_level"] or 0
        current_level = user_skill_levels.get(skill_id, 0)
        gap = max(required_level - current_level, 0)

        total_required += required_level
        total_current += min(current_level, required_level)

        gap_data.append(
            {
                "skill_name": req["skills"]["name"],
                "current_level": current_level,
                "required_level": required_level,
                "gap": gap,
                "importance": req["importance"] or 1,
            }
        )

    # Readiness percentage — same style of deterministic backend
    # math as the matching algorithm, not AI-derived.
    readiness_percentage = (
        round((total_current / total_required) * 100) if total_required > 0 else 0
    )

    valid_skill_names = {g["skill_name"] for g in gap_data}

    # ------------------------------------------------------------
    # CHECK FOR AN EXISTING ROADMAP FIRST — avoids wasting a Groq
    # API call and creating duplicate database rows every time the
    # user simply revisits this page for a career they've already
    # generated a roadmap for.
    #
    # NOTE: this does NOT check whether user_skills has changed
    # since the roadmap was generated (e.g. they retook an
    # assessment and improved). The existing roadmap is returned
    # as-is even if stale — staleness detection + regeneration is
    # planned for a future recalculation feature, not built here.
    # ------------------------------------------------------------
    existing_roadmap = (
        supabase.table("roadmaps")
        .select("id, readiness_percentage")
        .eq("profile_id", user_id)
        .eq("career_id", request.career_id)
        .execute()
    )

    if existing_roadmap.data:
        roadmap_id = existing_roadmap.data[0]["id"]
        readiness = existing_roadmap.data[0]["readiness_percentage"]

        existing_steps = (
            supabase.table("roadmap_steps")
            .select("id, step_order, title, description, resource_url, is_completed, skills(name)")
            .eq("roadmap_id", roadmap_id)
            .order("step_order")
            .execute()
        )

        return RoadmapResponse(
            roadmap_id=roadmap_id,
            career_title=career_title,
            readiness_percentage=readiness,
            already_existed=True,
            steps=[
                RoadmapStepOut(
                    step_id=s["id"],
                    step_order=s["step_order"],
                    title=s["title"],
                    description=s["description"],
                    skill_name=s["skills"]["name"] if s["skills"] else None,
                    resource_url=s["resource_url"],
                    is_completed=s["is_completed"] or False,
                )
                for s in (existing_steps.data or [])
            ],
        )


@router.post("/roadmap/recalculate", response_model=RoadmapResponse)
async def recalculate_roadmap(
    request: RoadmapRecalculateRequest,
    user_id: str = Depends(get_current_user_id),
):
    """
    Refreshes an existing roadmap against the user's CURRENT skill
    levels. This is the fix for a known limitation: a roadmap step
    generated when a skill was low (e.g. "learn SQL") stays sitting
    there even after the user later masters that skill via a real
    assessment or capped activity logging — this endpoint detects
    that and removes steps for skills that are no longer a gap.

    Steps are only ever REMOVED here if their skill's gap has
    dropped to 0 — never silently regenerated via a new Groq call,
    to avoid unnecessary AI cost/latency on every recalculation.
    """
    supabase = get_supabase()

    roadmap_result = (
        supabase.table("roadmaps")
        .select("id, career_id, profile_id")
        .eq("id", request.roadmap_id)
        .single()
        .execute()
    )

    if not roadmap_result.data:
        raise HTTPException(status_code=404, detail="Roadmap not found.")

    if roadmap_result.data["profile_id"] != user_id:
        raise HTTPException(
            status_code=403,
            detail="You do not have permission to recalculate this roadmap.",
        )

    career_id = roadmap_result.data["career_id"]

    career_result = (
        supabase.table("careers").select("title").eq("id", career_id).single().execute()
    )
    career_title = career_result.data["title"] if career_result.data else "Career"

    existing_steps_result = (
        supabase.table("roadmap_steps")
        .select("id, step_order, title, description, resource_url, is_completed, skill_id, skills(name)")
        .eq("roadmap_id", request.roadmap_id)
        .order("step_order")
        .execute()
    )
    existing_steps = existing_steps_result.data or []

    requirements_result = (
        supabase.table("career_skills")
        .select("skill_id, required_level")
        .eq("career_id", career_id)
        .execute()
    )
    requirements = requirements_result.data or []
    required_by_skill = {r["skill_id"]: r["required_level"] or 0 for r in requirements}

    skill_ids = [r["skill_id"] for r in requirements]
    user_skills_result = (
        supabase.table("user_skills")
        .select("skill_id, assessed_level")
        .eq("profile_id", user_id)
        .in_("skill_id", skill_ids)
        .execute()
    )
    user_skill_levels = {
        row["skill_id"]: row["assessed_level"] or 0
        for row in (user_skills_result.data or [])
    }

    steps_to_keep = []

    for step in existing_steps:
        skill_id = step["skill_id"]
        required_level = required_by_skill.get(skill_id, 0)
        current_level = user_skill_levels.get(skill_id, 0)

        still_has_gap = current_level < required_level

        if still_has_gap:
            steps_to_keep.append(step)
        else:
            supabase.table("roadmap_steps").delete().eq("id", step["id"]).execute()

    response_steps = []
    for i, step in enumerate(steps_to_keep, start=1):
        if step["step_order"] != i:
            supabase.table("roadmap_steps").update({"step_order": i}).eq(
                "id", step["id"]
            ).execute()

        response_steps.append(
            RoadmapStepOut(
                step_id=step["id"],
                step_order=i,
                title=step["title"],
                description=step["description"],
                skill_name=step["skills"]["name"] if step["skills"] else None,
                resource_url=step["resource_url"],
                is_completed=step["is_completed"] or False,
            )
        )

    total_required = 0
    total_current = 0
    for skill_id, required_level in required_by_skill.items():
        current_level = user_skill_levels.get(skill_id, 0)
        total_required += required_level
        total_current += min(current_level, required_level)

    readiness_percentage = (
        round((total_current / total_required) * 100) if total_required > 0 else 0
    )

    supabase.table("roadmaps").update(
        {"readiness_percentage": readiness_percentage}
    ).eq("id", request.roadmap_id).execute()

    return RoadmapResponse(
        roadmap_id=request.roadmap_id,
        career_title=career_title,
        readiness_percentage=readiness_percentage,
        already_existed=True,
        steps=response_steps,
    )
    # ------------------------------------------------------------
    # STEP 2 — Call Groq to generate the ordered, explained steps.
    # response_format="json_object" forces syntactically valid JSON
    # at the API level, on top of the prompt's own instructions.
    # ------------------------------------------------------------
    client = Groq(api_key=settings.groq_api_key)
    prompt = build_roadmap_prompt(career_title, gap_data)

    try:
        completion = client.chat.completions.create(
            model=settings.groq_model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,  # low temperature: structured task, not creative writing
            response_format={"type": "json_object"},
        )
        raw_response = completion.choices[0].message.content
    except Exception:
        raise HTTPException(
            status_code=502,
            detail="Failed to generate roadmap. The AI service may be temporarily unavailable.",
        )

    # ------------------------------------------------------------
    # STEP 3 — Validate the AI's response before trusting any of it.
    # ------------------------------------------------------------
    validated_steps = parse_and_validate_ai_response(raw_response, valid_skill_names)

    # ------------------------------------------------------------
    # STEP 4 — Save the roadmap and its steps to Supabase. Each
    # step's resource_url is looked up from our own curated
    # SKILL_RESOURCES dict, NEVER taken from the AI's response —
    # the AI was never even asked to produce one.
    # ------------------------------------------------------------
    roadmap_insert = (
        supabase.table("roadmaps")
        .insert(
            {
                "profile_id": user_id,
                "career_id": request.career_id,
                "readiness_percentage": readiness_percentage,
            }
        )
        .execute()
    )

    if not roadmap_insert.data:
        raise HTTPException(status_code=400, detail="Failed to save roadmap.")

    roadmap_id = roadmap_insert.data[0]["id"]

    # Build a skill_name -> skill_id lookup so we can store the
    # real foreign key alongside each step.
    skill_name_to_id = {
        req["skills"]["name"]: req["skill_id"] for req in requirements
    }

    step_records = []
    for i, step in enumerate(validated_steps, start=1):
        skill_id = skill_name_to_id.get(step["skill_name"])
        resource_url = SKILL_RESOURCES.get(step["skill_name"])

        step_records.append(
            {
                "roadmap_id": roadmap_id,
                "skill_id": skill_id,
                "step_order": i,
                "title": step["title"],
                "description": step["description"],
                "resource_url": resource_url,
                "is_completed": False,
            }
        )

    # Insert all steps, then read back the real database IDs Supabase
    # assigned — needed so the response includes each step's real
    # step_id (required for POST /progress/update and
    # POST /progress/activity to know which step to act on).
    insert_result = supabase.table("roadmap_steps").insert(step_records).execute()
    inserted_steps = insert_result.data or []

    response_steps = [
        RoadmapStepOut(
            step_id=inserted["id"],
            step_order=inserted["step_order"],
            title=inserted["title"],
            description=inserted["description"],
            skill_name=step["skill_name"],
            resource_url=inserted["resource_url"],
            is_completed=False,
        )
        for inserted, step in zip(inserted_steps, validated_steps)
    ]

    return RoadmapResponse(
        roadmap_id=roadmap_id,
        career_title=career_title,
        readiness_percentage=readiness_percentage,
        already_existed=False,
        steps=response_steps,
    )